;;
;; Copyright @ 2025 Oslo University Hospital
;;
;; This file is part of SystoleOS.
;;
;; SystoleOS is free software: you can redistribute it and/or modify it under the
;; terms of the GNU General Public License as published by the Free Software
;; Foundation, either version 3 of the License, or (at your option) any later version.
;;
;; SystoleOS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
;; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
;; PURPOSE. See the GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License along
;; with SystoleOS. If not, see <https://www.gnu.org/licenses/>.
;;

(define-module (systole packages claude-skills)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix build-system trivial)
  #:use-module (guix gexp)
  #:use-module (guix packages)
  #:use-module (systole packages ctk)
  #:use-module (systole packages itk)
  #:use-module (systole packages slicer)
  #:use-module (systole packages vtk))

;;;
;;; Factory
;;;
;;; Each skill package installs:
;;;   share/claude-skills/<name>/SKILL.md
;;;   share/claude-skills/<name>/block-content.md   <- pre-rendered block body
;;;   share/claude-skills/<name>/<dest>/             <- for each extra-data entry
;;;   bin/<name>-skill                               <- shell script
;;;
;;; The shell script exposes:
;;;   <name>-skill block [--type TYPE]  — print CLAUDE.md snippet
;;;   <name>-skill status               — print resolved data paths

(define* (make-claude-skill
          #:key
          name
          version
          skill-md            ; local-file pointing to SKILL.md
          (extra-data '())    ; ((dest-name . local-file-or-derivation) ...)
          block-content       ; computed-file / local-file with block body markdown
                              ;   (all data-source paths baked in at build time;
                              ;    the runtime SKILL_DIR prefix is added by the script)
          (extra-cases '())   ; ((case-name . shell-body-string) ...) — extra case branches
          synopsis
          description
          home-page
          license
          (propagated-inputs '()))
  "Build a trivial Claude skill package.

SKILL-MD is a local-file for the SKILL.md to install.
EXTRA-DATA is a list of (DEST-NAME . SRC) pairs; each SRC is copied into
share/claude-skills/NAME/DEST-NAME/ at build time.
BLOCK-CONTENT is a computed-file whose content becomes the body of the
`block` output (everything after the skill-location header line)."
  ;; Capture the skill name before the (package ...) form.  Guix's
  ;; define-record-type* evaluates field expressions in a letrec-like scope
  ;; where the field identifier `name` shadows the outer #:name argument.
  (let ((skill-name name))
  (package
    (name (string-append skill-name "-skill"))
    (version version)
    (source #f)
    (build-system trivial-build-system)
    (native-inputs '())
    (propagated-inputs propagated-inputs)
    (arguments
     (list
      #:builder
      (with-imported-modules '((guix build utils))
        #~(begin
            (use-modules (guix build utils))

            (let* ((skill-dir (string-append #$output
                                             "/share/claude-skills/"
                                             #$skill-name))
                   (bin-dir   (string-append #$output "/bin"))
                   (script    (string-append bin-dir "/" #$skill-name "-skill")))

              ;; Install SKILL.md
              (mkdir-p skill-dir)
              (copy-file #$skill-md
                         (string-append skill-dir "/SKILL.md"))

              ;; Install pre-rendered block body
              (copy-file #$block-content
                         (string-append skill-dir "/block-content.md"))

              ;; Install extra data directories
              #$@(map (lambda (pair)
                        (let ((dest (car pair))
                              (src  (cdr pair)))
                          #~(let ((dst (string-append
                                        #$output
                                        "/share/claude-skills/"
                                        #$skill-name "/" #$dest)))
                              (mkdir-p dst)
                              (copy-recursively #$src dst))))
                      extra-data)

              ;; Generate bin/<name>-skill
              (mkdir-p bin-dir)
              (call-with-output-file script
                (lambda (port)
                  (display
                   (string-append
                    "#!/bin/sh\n"
                    "# Claude skill: " #$skill-name " — generated by make-claude-skill\n"
                    "SKILL_DIR='" skill-dir "'\n"
                    "cmd=\"${1:-block}\"\n"
                    "shift 2>/dev/null || true\n"
                    "\n"
                    "case \"$cmd\" in\n"
                    "  block)\n"
                    "    printf '## " #$skill-name " skill\\n\\n'\n"
                    "    printf 'Skill located at:\\n\\n'\n"
                    "    printf '    %s\\n\\n' \"$SKILL_DIR\"\n"
                    "    cat \"$SKILL_DIR/block-content.md\"\n"
                    "    ;;\n"
                    "  status)\n"
                    "    printf 'Skill   : " #$skill-name "\\n'\n"
                    "    printf 'SKILL.md: %s/SKILL.md\\n' \"$SKILL_DIR\"\n"
                    "    printf 'block   : %s/block-content.md\\n' \"$SKILL_DIR\"\n"
                    #$@(map (lambda (pair)
                              (let ((dest (car pair)))
                                (string-append
                                 "    printf '" dest ": %s/" dest "\\n' \"$SKILL_DIR\"\n")))
                            extra-data)
                    "    ;;\n"
                    #$@(map (lambda (pair)
                              (let ((cname (car pair))
                                    (body  (cdr pair)))
                                (string-append
                                 "  " cname ")\n"
                                 body
                                 "\n    ;;\n")))
                            extra-cases)
                    "  *)\n"
                    "    printf 'Usage: " #$skill-name "-skill {block|status"
                    #$@(map (lambda (p) (string-append "|" (car p))) extra-cases)
                    "}\\n' >&2\n"
                    "    exit 1\n"
                    "    ;;\n"
                    "esac\n")
                   port)))
              (chmod script #o755))))))
    (synopsis synopsis)
    (description description)
    (home-page home-page)
    (license license))))

;;;
;;; guix-systole-dev-skill
;;;

;; Capture guix-systole .scm source files.  The local-file path resolves
;; relative to this file's location (systole/systole/packages/), so
;; "../../.." reaches the repository root.
(define guix-systole-scm-source
  (local-file "../../.."
              "guix-systole-source"
              #:recursive? #t
              #:select?
              (lambda (path stat)
                (let ((base (basename path)))
                  (cond
                   ;; Descend into dirs, excluding large/irrelevant ones
                   ((eq? (stat:type stat) 'directory)
                    (not (member base '(".git" "assets" "tests" "docs"
                                       "system" "scripts" "deployment"
                                       ".claude" "slicer-skill" "patches"))))
                   ;; Include all .scm files
                   ((string-suffix? ".scm" base) #t)
                   ;; Include key top-level docs and skill files
                   ((string-suffix? ".md" base) #t)
                   (else #f))))))

(define %guix-systole-dev-block-content
  (computed-file
   "guix-systole-dev-block-content.md"
   #~(call-with-output-file #$output
       (lambda (port)
         (display
          (string-append
           "That directory contains `SKILL.md` with a two-layer reference:\n"
           "Layer 1 covers GNU Guix fundamentals (packages, gexps, build systems,\n"
           "local-file, computed-file, factory patterns, trivial builds);\n"
           "Layer 2 documents the guix-systole Slicer patch workflow (branch naming,\n"
           "git format-patch, make-slicer-loadable-module, inter-module dependency\n"
           "wiring, CMakeLists preambles, known build issues, testing commands).\n"
           "\n"
           "**Immutable store paths (no setup required):**\n"
           "\n"
           "| Content | Store path |\n"
           "|---|---|\n"
           "| guix-systole .scm files | `"
           #$(file-append guix-systole-scm-source) "` |\n"
           "\n"
           "**Mutable path (configure in your CLAUDE.md):**\n"
           "\n"
           "```sh\n"
           "# EDIT THIS — point at your Slicer-Systole checkout:\n"
           "export SLICER_SYSTOLE_DIR=~/src/Slicer/Slicer-Systole\n"
           "```\n"
           "\n"
           "Run `guix-systole-dev-skill setup` to clone Slicer-Systole if not present.\n"
           "\n"
           "**Quick search examples:**\n"
           "```bash\n"
           "# Find make-slicer-loadable-module usage patterns\n"
           "grep -n 'make-slicer-loadable-module' "
           #$(file-append guix-systole-scm-source)
           "/systole/systole/packages/slicer.scm | head -20\n"
           "\n"
           "# Find inter-module dependency patterns\n"
           "grep -B2 -A8 'extra-configure-flags' "
           #$(file-append guix-systole-scm-source)
           "/systole/systole/packages/slicer.scm | head -50\n"
           "\n"
           "# List existing patch subdirectories\n"
           "ls " #$(file-append guix-systole-scm-source)
           "/systole/systole/packages/patches/slicer/\n"
           "```\n")
          port)))))

(define-public guix-systole-dev-skill
  (make-claude-skill
   #:name "guix-systole-dev"
   #:version "5.8.1"

   #:skill-md
   (local-file "skills/guix-systole-dev/SKILL.md")

   #:extra-data
   (list (cons "source" guix-systole-scm-source))

   #:block-content %guix-systole-dev-block-content

   #:extra-cases
   (list
    (cons "setup"
          (string-append
           "    DEV_DIR=\"${SLICER_SYSTOLE_DIR:-$HOME/src/Slicer/Slicer-Systole}\"\n"
           "    if [ -d \"$DEV_DIR/.git\" ]; then\n"
           "      printf 'Slicer-Systole already at %s\\n' \"$DEV_DIR\"\n"
           "    else\n"
           "      mkdir -p \"$(dirname \"$DEV_DIR\")\"\n"
           "      git clone https://github.com/SystoleOS/Slicer.git \"$DEV_DIR\"\n"
           "      printf 'Cloned to %s\\n' \"$DEV_DIR\"\n"
           "    fi\n"
           "    printf '\\nAdd to your CLAUDE.md:\\n'\n"
           "    printf '    export SLICER_SYSTOLE_DIR=%s\\n' \"$DEV_DIR\"")))

   #:synopsis "Claude skill for guix-systole channel development"
   #:description
   "Provides Claude Code with Guix-managed access to the guix-systole channel
source files (@file{.scm} package definitions) at content-addressed store
paths, plus a two-layer @file{SKILL.md} covering GNU Guix channel concepts
and the guix-systole Slicer patch workflow.

Run @command{guix-systole-dev-skill block} for a ready-to-paste CLAUDE.md
snippet.  Run @command{guix-systole-dev-skill setup} to clone the
Slicer-Systole development fork."
   #:home-page "https://github.com/SystoleOS/guix-systole"
   #:license license:gpl3+))

;;;
;;; slicer-skill
;;;

;; Block body for slicer-skill.  All data-source store paths are baked in via
;; #$(file-append ...) at package build time.  The SKILL_DIR prefix (runtime)
;; is prepended by the generated script.
(define %slicer-block-content
  (computed-file
   "slicer-block-content.md"
   #~(call-with-output-file #$output
       (lambda (port)
         (display
          (string-append
           "That directory contains `SKILL.md` with a two-layer reference:\n"
           "Layer 1 covers standard Slicer development (MRML, modules, Python API,\n"
           "VTK/ITK/CTK patterns, script repository); Layer 2 documents\n"
           "guix-systole-specific runtime behavior (module discovery, PYTHONPATH,\n"
           "build configuration, standalone module CMakeLists conventions).\n"
           "\n"
           "**Data paths (immutable Guix store, no setup required):**\n"
           "\n"
           "| Variable | Store path |\n"
           "|---|---|\n"
           "| Slicer source | `" #$(file-append slicer-source-5.8) "` |\n"
           "| VTK source    | `" #$(file-append vtk-slicer-source) "` |\n"
           "| ITK source    | `" #$(file-append itk-slicer-source) "` |\n"
           "| CTK source    | `" #$(file-append ctk-source) "` |\n"
           "\n"
           "The guix-systole patches applied to Slicer are at:\n"
           "`$SKILL_DIR/patches/` (see Layer 2 in SKILL.md for a patch index).\n"
           "\n"
           "**Quick search examples:**\n"
           "```bash\n"
           "grep -rn 'class qSlicerMarkupsModule' "
           #$(file-append slicer-source-5.8) "/\n"
           "grep -rn 'slicerMacroBuildLoadableModule' "
           #$(file-append slicer-source-5.8) "/Modules/Loadable/\n"
           "find " #$(file-append slicer-source-5.8)
           "/Libs/MRML/Core -name 'vtkMRML*Node.h'\n"
           "grep -rn 'class CTK_EXPORT' " #$(file-append ctk-source) "/\n"
           "```\n")
          port)))))

(define-public slicer-skill
  (make-claude-skill
   #:name "slicer"
   #:version "5.8.1"

   #:skill-md
   (local-file "skills/slicer/SKILL.md")

   ;; The guix-systole patches applied to Slicer — installed so Claude can
   ;; search them for Layer 2 context (runtime behavior differences).
   #:extra-data
   (list (cons "patches"
               (local-file "patches/slicer" #:recursive? #t)))

   #:block-content %slicer-block-content

   ;; All source packages at the exact commits the compiled packages use.
   #:propagated-inputs
   (list slicer-source-5.8
         vtk-slicer-source
         itk-slicer-source
         ctk-source)

   #:synopsis "Claude skill for 3D Slicer development"
   #:description
   "Provides Claude Code with Guix-managed access to 3D Slicer and its core
dependency sources (VTK, ITK, CTK) at content-addressed store paths, plus the
guix-systole patch corpus.  No setup or cloning required.

Includes a two-layer @file{SKILL.md}: Layer 1 covers standard Slicer development
(MRML scene graph, loadable/scripted/CLI modules, Python API, script repository,
VTK/ITK/CTK pipeline patterns, extension development); Layer 2 documents
guix-systole-specific runtime behavior (module discovery via
@env{SLICER_ADDITIONAL_MODULE_PATHS}, @env{PYTHONPATH} assembly,
@env{LD_LIBRARY_PATH} extension, build configuration differences, and standalone
module CMakeLists conventions).

Run @command{slicer-skill block} to output a ready-to-paste CLAUDE.md snippet."
   #:home-page "https://www.slicer.org"
   #:license license:bsd-3))
