#!/usr/bin/env bash
# Prepare a guix deploy deployment.scm from a USB-installed Systole target
# Copyright © 2026 Rafael Palomar <rafael.palomar@ous-research.no>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Usage: prepare-deployment.sh --key PRIVATE_KEY --host TARGET_IP [--port PORT] [--output FILE]

set -euo pipefail

PRIVATE_KEY=""
TARGET_HOST=""
TARGET_PORT=22
OUTPUT="deployment.scm"
CONFIG_LOCAL="target-config.scm"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

usage() {
    cat <<EOF
Usage: $0 --key PRIVATE_KEY --host TARGET_IP [OPTIONS]

Retrieve the generated config.scm from a USB-installed Systole target and
produce a deployment.scm suitable for 'guix deploy' / sync-and-deploy.sh.

OPTIONS:
    --key FILE      Path to the SSH private key (matching the deploy key embedded in ISO)
    --host IP       IP address or hostname of the installed target
    --port PORT     SSH port on the target (default: 22)
    --output FILE   Output deployment.scm path (default: deployment.scm)
    -h, --help      Show this help message

EXAMPLES:
    $0 --key ~/.ssh/deploy_key --host 192.168.1.50
    $0 --key ~/.ssh/deploy_key --host 192.168.1.50 --port 22 --output my-deployment.scm
EOF
    exit 0
}

error() {
    echo -e "${RED}ERROR: $*${NC}" >&2
    exit 1
}

info() {
    echo -e "${GREEN}INFO: $*${NC}"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --key)
            [[ -z "${2:-}" ]] && error "No key specified after --key"
            PRIVATE_KEY="$2"
            shift 2
            ;;
        --host)
            [[ -z "${2:-}" ]] && error "No host specified after --host"
            TARGET_HOST="$2"
            shift 2
            ;;
        --port)
            [[ -z "${2:-}" ]] && error "No port specified after --port"
            TARGET_PORT="$2"
            shift 2
            ;;
        --output)
            [[ -z "${2:-}" ]] && error "No output file specified after --output"
            OUTPUT="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            error "Unknown option: $1\nUse --help for usage information."
            ;;
    esac
done

[[ -z "$PRIVATE_KEY" ]] && error "--key is required"
[[ -z "$TARGET_HOST" ]] && error "--host is required"
[[ ! -f "$PRIVATE_KEY" ]] && error "Private key not found: $PRIVATE_KEY"

SSH_OPTS="-i $PRIVATE_KEY -p $TARGET_PORT -o StrictHostKeyChecking=no -o BatchMode=yes"

# Step 1: Verify connectivity
info "Verifying SSH connectivity to root@$TARGET_HOST:$TARGET_PORT ..."
if ! ssh $SSH_OPTS root@"$TARGET_HOST" true 2>/dev/null; then
    error "Cannot connect to root@$TARGET_HOST:$TARGET_PORT with key $PRIVATE_KEY"
fi
info "Connected successfully."

# Step 2: Retrieve config.scm
info "Retrieving /etc/config.scm from target ..."
if ! scp -P "$TARGET_PORT" -i "$PRIVATE_KEY" \
        -o StrictHostKeyChecking=no -o BatchMode=yes \
        root@"$TARGET_HOST":/etc/config.scm "$CONFIG_LOCAL"; then
    error "Failed to retrieve /etc/config.scm from target"
fi
info "Saved to: $CONFIG_LOCAL"

# Resolve absolute path for the identity key (deployment.scm needs it at deploy time)
ABS_KEY="$(cd "$(dirname "$PRIVATE_KEY")" && pwd)/$(basename "$PRIVATE_KEY")"

# Step 3: Generate deployment.scm
info "Generating $OUTPUT ..."
cat > "$OUTPUT" <<SCHEME
;; Auto-generated by prepare-deployment.sh
;; Target: $TARGET_HOST:$TARGET_PORT
;; Edit host-name, identity, system, and operating-system as needed.

(use-modules (gnu machine)
             (gnu machine ssh))

(list (machine
       (operating-system (load "$(realpath --relative-to="$(dirname "$OUTPUT")" "$CONFIG_LOCAL")"))
       (environment managed-host-environment-type)
       (configuration (machine-ssh-configuration
                       (host-name "$TARGET_HOST")
                       (system "x86_64-linux")
                       (port $TARGET_PORT)
                       (user "root")
                       (identity "$ABS_KEY")))))
SCHEME

info "Deployment file written to: $OUTPUT"
echo ""
echo -e "${GREEN}===== Next Step =====${NC}"
echo "Deploy to the target machine:"
echo "   ./scripts/sync-and-deploy.sh $OUTPUT"
